
a2lix_translation_form:
    locale_provider: default       # [1]
    locales: '%app.supported_locales%'      # [1-a]
    default_locale: '%kernel.default_locale%'             # [1-b]
    required_locales: '%app.supported_locales%'           # [1-c]
    templating: "@A2lixTranslationForm/bootstrap_4_layout.html.twig"      # [2]

a2lix_auto_form:
    excluded_fields: [id, locale, translatable]       # [1]
