framework:
    default_locale: 'en_US'
    enabled_locales: ['en_US', 'fr_FR']
    translator:
        default_path: '%kernel.project_dir%/translations'
        providers:
            lokalise:
                dsn: '%env(LOKALISE_DSN)%'
